
services:
  - type: web
    name: calmcompass-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py  
    envVars:
      - key: OPENWEATHER_API_KEY
        value: your_actual_key
    plan: free
    region: oregon
    rootDir: backend